# Generated by Django 5.1.3 on 2025-01-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_post_alter_antrenor_ozet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('soyadi', models.CharField(max_length=30)),
                ('anne', models.CharField(max_length=30)),
                ('baba', models.CharField(max_length=30)),
                ('dogum_tarihi', models.DateField()),
                ('okulu', models.CharField(max_length=30)),
                ('resim', models.ImageField(upload_to='media/')),
                ('telefon', models.CharField(max_length=10)),
                ('telefon_veli', models.CharField(max_length=10)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='antrenor',
            name='resim',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Ozellikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.IntegerField()),
                ('kilo', models.IntegerField()),
                ('tarih', models.DateField(auto_now_add=True)),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sporcu')),
            ],
        ),
        migrations.AddField(
            model_name='sporcu',
            name='takim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.takim'),
        ),
        migrations.CreateModel(
            name='Antrenman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.DateField(auto_now_add=True)),
                ('mesafe', models.IntegerField()),
                ('sporcular', models.ManyToManyField(to='main.sporcu')),
                ('takimlar', models.ManyToManyField(to='main.takim')),
            ],
        ),
    ]
