# Generated by Django 5.1.3 on 2025-01-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sporcu_takim_alter_antrenor_resim_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozellikler',
            name='sporcu',
        ),
        migrations.RemoveField(
            model_name='sporcu',
            name='takim',
        ),
        migrations.DeleteModel(
            name='Antrenman',
        ),
        migrations.DeleteModel(
            name='Ozellikler',
        ),
        migrations.DeleteModel(
            name='Sporcu',
        ),
        migrations.DeleteModel(
            name='Takim',
        ),
    ]
