# Generated by Django 5.1.5 on 2025-01-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('soyadi', models.CharField(max_length=30)),
                ('anne', models.CharField(max_length=30)),
                ('baba', models.CharField(max_length=30)),
                ('dogum_tarihi', models.DateField()),
                ('okulu', models.CharField(max_length=30)),
                ('resim', models.ImageField(upload_to='media/')),
                ('telefon', models.CharField(max_length=10)),
                ('telefon_veli', models.CharField(max_length=10)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ozellikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.IntegerField()),
                ('kilo', models.IntegerField()),
                ('tarih', models.DateField(auto_now_add=True)),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.sporcu')),
            ],
        ),
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('aktif', models.BooleanField(default=True)),
                ('antrenor', models.ManyToManyField(to='main.antrenor')),
            ],
        ),
        migrations.AddField(
            model_name='sporcu',
            name='takim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.takim'),
        ),
        migrations.CreateModel(
            name='HaftalikAntrenman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.IntegerField(choices=[(0, 'Pazar'), (1, 'Pazartesi'), (2, 'Sali'), (3, 'Carsamba'), (4, 'Persembe'), (5, 'Cuma'), (6, 'Cumartesi')])),
                ('saat', models.TimeField()),
                ('yer', models.TextField(choices=[('Hacettepe', 'Hacettepe'), ('Atlas', 'Atlas')], null=True)),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.takim')),
            ],
        ),
        migrations.CreateModel(
            name='Antrenman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.DateField()),
                ('mesafe', models.IntegerField()),
                ('sporcular', models.ManyToManyField(blank=True, null=True, to='takim.sporcu')),
                ('takimlar', models.ManyToManyField(to='takim.takim')),
            ],
            options={
                'ordering': ['-gun'],
            },
        ),
    ]
