# Generated by Django 5.1.5 on 2025-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haftalikantrenman',
            name='tur',
            field=models.TextField(choices=[('Yüzme', 'Yüzme'), ('Kara', 'Kara')], null=True),
        ),
    ]
