# Generated by Django 5.1.3 on 2025-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_ozellikler_sporcu_remove_sporcu_takim_and_more'),
        ('takim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='antrenor',
            field=models.ManyToManyField(to='main.antrenor'),
        ),
    ]
