# Generated by Django 5.1.3 on 2025-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0002_takim_antrenor'),
    ]

    operations = [
        migrations.AddField(
            model_name='takim',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
