# Generated by Django 5.1.3 on 2025-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0003_takim_resim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antrenman',
            options={'ordering': ['-gun']},
        ),
        migrations.AlterField(
            model_name='antrenman',
            name='sporcular',
            field=models.ManyToManyField(blank=True, null=True, to='takim.sporcu'),
        ),
    ]
