# Generated by Django 5.1.3 on 2025-01-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0004_alter_antrenman_options_alter_antrenman_sporcular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrenman',
            name='gun',
            field=models.DateField(),
        ),
    ]
