# Generated by Django 5.1.3 on 2025-01-19 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0005_alter_antrenman_gun'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaftalikAntrenman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.IntegerField(choices=[(0, 'Pazar'), (1, 'Pazartesi'), (2, 'Sali'), (3, 'CArsamba'), (4, 'Persembe'), (5, 'Cuma'), (6, 'Cumartesi')])),
                ('saat', models.TimeField()),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takim.takim')),
            ],
        ),
    ]
