# Generated by Django 5.1.3 on 2025-01-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takim', '0006_haftalikantrenman'),
    ]

    operations = [
        migrations.AddField(
            model_name='haftalikantrenman',
            name='yer',
            field=models.TextField(choices=[('Hacettepe', 'Hacettepe'), ('Atlas', 'Atlas')], null=True),
        ),
    ]
